# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: synerzip
  password: synerzip
  host: 127.0.0.1


development:
  <<: *default
  database: myapp_dev

test:
  <<: *default
  database: myapp_test